version: '3.8'

services:
  mail-sender:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped 